### ISSUE TITLE
draw_valid_moves() issue

### ISSUE THREAD

**Issue by DaringT** [techwithtim/Python-Checkers#2]
The draw_valid_moves(), line 55 is hit or miss especially misses on longer jumps show below.

![checker bug2](https://user-images.githubusercontent.com/71405559/93380929-eeb0c380-f82d-11ea-9043-61b311adbb07.PNG)
![checker bug](https://user-images.githubusercontent.com/71405559/93380930-eeb0c380-f82d-11ea-9716-487c226d2789.PNG)

**Comment by Nevesgmd** [comment]
I found out how to fix the bug. It's on _traverse_left and _traverse_right methods of the Board class. The code is actually passing the minimum value of the max () function as 0, when in fact it should be -1. Changing this line corrects the double jump issue :)
