### ISSUE TITLE
Crown

### ISSUE THREAD

**Issue by JoelTech43** [techwithtim/Python-Checkers#6]
Hi!
Just a question but when I looked through the code I saw the directory assets/crown.png or something like that. However, looking through the files on this repo, there is no file called that!
Could you help me please?

**Comment by bdesaedeleer** [comment]
You can download the asset via the link in the description of this video: https://www.youtube.com/watch?v=LSYj8GZMjWY
Just unzip the file and save the image as crown.png in an assets folder

**Comment by JoelTech43** [comment]
Thank you very much!
